#include "init_launch.h"
#include "init_launch_internal.h"
#include "../lib/types.h"
#include "../lib/string.h"
#include "../serial/serial.h"
#include "../pmm/pmm.h"
#include "../vmm/vmm.h"
#include "../vmm/vmm_internal.h"
#include "../elf/elf.h"
#include "../process/process.h"
#include "../process/process_internal.h"
#include "../scheduler/scheduler.h"
#include "../gdt/gdt.h"
#include "../syscall/syscall.h"
#include "../vfs/vfs.h"
#include "../devfs/devfs.h"
#include "../heap/heap.h"

/* ── Embedded ELF images — generated by `make userspace` via xxd ────── */
extern const u8  init_elf_data[];
extern const u32 init_elf_size;
extern const u8  httpd_elf_data[];
extern const u32 httpd_elf_size;

/* ── Segment selectors (from gdt_internal.h) ────────────────────────── */
#define SEG_USER_CODE  0x23u   /* GDT_USER_CODE * 8 | RPL3 */
#define SEG_USER_DATA  0x1Bu   /* GDT_USER_DATA * 8 | RPL3 */

/* ── iretq trampoline — defined in init_launch_entry.asm ────────────── */
extern void init_iretq_trampoline(void);

/* ── alloc_user_stack ────────────────────────────────────────────────
   Map USTACK_PAGES pages of user stack below USTACK_TOP in pml4_phys.
   Returns USTACK_TOP on success, 0 on OOM. */
static u64 alloc_user_stack(u64 pml4_phys) {
    for (u32 i = 0; i < USTACK_PAGES; i++) {
        u64 frame = pmm_alloc_frame();
        if (!frame) return 0;
        memset((void *)(usize)frame, 0, PAGE_SIZE);
        u64 vaddr = USTACK_TOP - (u64)(USTACK_PAGES - i) * PAGE_SIZE;
        u64 flags = PTE_USER | PTE_WRITE;
        if (vmm_map_user_page(pml4_phys, vaddr, frame, flags) != 0) {
            pmm_free_frame(frame);
            return 0;
        }
    }
    return USTACK_TOP;
}

/* ── launch_user_process ─────────────────────────────────────────────
   Generic kernel-side ELF launcher.  Used for httpd (and any future
   processes that don't need to own fds 0/1/2).
   kstack is kmalloc'd into the higher-half — accessible from all PML4s
   so interrupt handlers work regardless of which CR3 is loaded.      */
static int launch_user_process(const char *name,
                                const u8 *elf_data, u32 elf_size) {
    u64 pml4_phys = vmm_create_user_pml4();
    if (!pml4_phys) return -1;

    u64 entry = 0;
    if (elf_load(elf_data, (usize)elf_size, pml4_phys, &entry) != 0) {
        klog(LOG_ERROR, "[init] ELF load failed for %s", name);
        return -1;
    }

    u64 ustack_top = alloc_user_stack(pml4_phys);
    if (!ustack_top) {
        klog(LOG_ERROR, "[init] user stack OOM for %s", name);
        return -1;
    }

    /* Kernel stack via kmalloc — lives in higher-half (PML4[511]),
       present in every address space; no need to map it explicitly. */
    u8 *kstack = (u8 *)kmalloc(KSTACK_SIZE);
    if (!kstack) return -1;
    memset(kstack, 0, KSTACK_SIZE);

    /* Build iretq frame at top of kernel stack */
    u64  kstack_top = (u64)(usize)(kstack + KSTACK_SIZE);
    u64 *frame      = (u64 *)kstack_top;
    *(--frame) = (u64)SEG_USER_DATA;
    *(--frame) = ustack_top;
    *(--frame) = USER_RFLAGS;
    *(--frame) = (u64)SEG_USER_CODE;
    *(--frame) = entry;
    u64 kstack_rsp = (u64)(usize)frame;

    i32 pid = kthread_create(name, init_iretq_trampoline);
    if (pid < 0) { kfree(kstack); return -1; }

    process_t *p = process_get((u32)pid);
    kfree(p->kstack);
    p->kstack    = kstack;
    p->pml4_phys = pml4_phys;
    p->ctx.rsp   = kstack_rsp;
    p->ctx.rip   = (u64)(usize)init_iretq_trampoline;

    scheduler_add(p);
    klog(LOG_INFO, "[init] launched '%s' pid=%d entry=0x%x",
         name, (int)pid, (unsigned)entry);
    return 0;
}

/* ── init_launch_impl ────────────────────────────────────────────────
   1. Open /dev/tty0 as fds 0/1/2.
   2. Create a new user PML4.
   3. Load the init ELF into it.
   4. Map a user stack.
   5. Allocate a kernel stack and build an iretq frame on it.
   6. Enqueue a new process_t that will iretq into userspace on first schedule. */
static int init_launch_impl(void) {
    /* ── 1. Open stdin/stdout/stderr → /dev/tty0 ── */
    vfs_node_t tty_node;
    if (devfs_get_node("tty0", &tty_node) != 0) {
        klog(LOG_ERROR, "[init] /dev/tty0 not found");
        return -1;
    }
    /* Open three times: stdin(0), stdout(1), stderr(2) */
    for (int i = 0; i < 3; i++) {
        int fd = vfs_fd_open(&tty_node);
        if (fd != i) {
            klog(LOG_ERROR, "[init] expected fd %d, got %d", i, fd);
            return -1;
        }
    }
    klog(LOG_DEBUG, "[init] fds 0/1/2 → /dev/tty0");

    /* ── 2. Create user address space ── */
    u64 pml4_phys = vmm_create_user_pml4();
    if (!pml4_phys) {
        klog(LOG_ERROR, "[init] failed to create user PML4");
        return -1;
    }

    /* ── 3. Load ELF ── */
    u64 entry = 0;
    if (elf_load(init_elf_data, (usize)init_elf_size, pml4_phys, &entry) != 0) {
        klog(LOG_ERROR, "[init] ELF load failed");
        return -1;
    }

    /* ── 4. Map user stack ── */
    u64 ustack_top = alloc_user_stack(pml4_phys);
    if (!ustack_top) {
        klog(LOG_ERROR, "[init] user stack OOM");
        return -1;
    }

    /* ── 5. Allocate kernel stack (page-aligned) and build iretq frame ──
       pmm_alloc_frame gives a page-aligned frame; use two consecutive frames
       for 8 KB.  We can't use kmalloc here because it may return unaligned
       addresses, which breaks the page-table mapping loop below. */
    u64 kstack_frame0 = pmm_alloc_frame();
    u64 kstack_frame1 = pmm_alloc_frame();
    if (!kstack_frame0 || !kstack_frame1) {
        klog(LOG_ERROR, "[init] kstack OOM");
        if (kstack_frame0) pmm_free_frame(kstack_frame0);
        return -1;
    }
    /* Zero both frames */
    memset((void *)(usize)kstack_frame0, 0, PAGE_SIZE);
    memset((void *)(usize)kstack_frame1, 0, PAGE_SIZE);
    u8 *kstack = (u8 *)(usize)kstack_frame0;

    /* Stack top = top of kstack_frame1.
       Build the iretq frame: iretq pops RIP, CS, RFLAGS, user-RSP, SS. */
    u64 kstack_top = kstack_frame1 + PAGE_SIZE;
    u64 *frame = (u64 *)kstack_top;
    *(--frame) = (u64)SEG_USER_DATA;   /* SS       */
    *(--frame) = ustack_top;           /* user RSP */
    *(--frame) = USER_RFLAGS;          /* RFLAGS   */
    *(--frame) = (u64)SEG_USER_CODE;   /* CS       */
    *(--frame) = entry;                /* RIP      */

    /* RSP for context_switch: points at the bottom of the iretq frame */
    u64 kstack_rsp = (u64)(usize)frame;

    klog(LOG_DEBUG, "[init] kstack0=0x%x kstack1=0x%x rsp0=0x%x kstack_rsp=0x%x",
         (unsigned)kstack_frame0, (unsigned)kstack_frame1,
         (unsigned)kstack_top, (unsigned)kstack_rsp);

    /* ── 5b. Map kstack frames into user PML4 (ring-0 only, no PTE_USER) ──
       kstack_frame0 and kstack_frame1 are page-aligned physical addresses.
       Map them at the same VA (identity: phys == virt) so the kernel can
       access them when CR3 = init's PML4 (interrupt/exception stack). */
    if (vmm_map_kernel_in_user_pml4(pml4_phys, kstack_frame0, kstack_frame0,
                                    PTE_WRITE | PTE_NX) != 0 ||
        vmm_map_kernel_in_user_pml4(pml4_phys, kstack_frame1, kstack_frame1,
                                    PTE_WRITE | PTE_NX) != 0) {
        klog(LOG_ERROR, "[init] failed to map kstack frames");
        return -1;
    }
    klog(LOG_DEBUG, "[init] kstack frames 0x%x/0x%x mapped in user PML4",
         (unsigned)kstack_frame0, (unsigned)kstack_frame1);

    /* ── 6. Create process_t ── */
    /* Use kthread_create to get a pid and set up the slot, then override. */
    i32 pid = kthread_create("init", init_iretq_trampoline);
    if (pid < 0) {
        klog(LOG_ERROR, "[init] kthread_create failed");
        return -1;
    }
    process_t *p = process_get((u32)pid);

    /* kthread_create allocated its own kstack — free it; use our PMM-allocated
       page-aligned kstack instead. */
    kfree(p->kstack);
    p->kstack     = kstack;
    p->pml4_phys  = pml4_phys;
    p->ctx.rsp    = kstack_rsp;
    p->ctx.rip    = (u64)(usize)init_iretq_trampoline;
    /* Other callee-saved regs are zero — fine for a fresh thread */
    klog(LOG_DEBUG, "[init] ctx.rsp=0x%x ctx.rip=0x%x",
         (unsigned)p->ctx.rsp, (unsigned)p->ctx.rip);

    /* ── 7. Update TSS RSP0 (interrupts) and SYSCALL kernel RSP ── */
    gdt_set_tss_rsp0(kstack_top);
    syscall_set_kernel_rsp(kstack_top);

    /* ── 8. Add to scheduler run queue ── */
    scheduler_add(p);

    klog(LOG_INFO, "[init] launching PID %d entry=0x%x usp=0x%x",
         (int)pid, (unsigned)entry, (unsigned)ustack_top);

    /* ── 9. Launch httpd as an independent kernel-spawned process ──
       Done here (not from userspace init) so httpd gets its own clean
       PML4 — avoids the race where two concurrent execve calls on COW
       clones of the same parent corrupt each other's address spaces.  */
    if (launch_user_process("httpd", httpd_elf_data, httpd_elf_size) < 0)
        klog(LOG_WARN, "[init] httpd launch failed (non-fatal)");

    return 0;
}

static void init_launch_dump(void) {
    klog(LOG_DEBUG, "[init] init launch module ready");
}

kernel_module_t mod_init_launch = {
    .name        = "init_launch",
    .init        = init_launch_impl,
    .dump        = init_launch_dump,
    .initialized = false,
};
